workspace:
  base: /go

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo


  latest:
    image: plugins/docker
    repo: ipedrazas/drone-helm
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push
        
plugin:
  name: drone-helm
  desc: Execute helm to 
  type: deploy
  image: ipedrazas/drone-helm
  labels:
    - deploy
    - kubernetes
    - helm